version: 1.0.{build}
init:
  - SET PGUSER=postgres
  - SET PGPASSWORD=Password12!
  - PATH=C:\Program Files\PostgreSQL\9.6\bin\;%PATH%
install:
  - nuget restore ./csharp/Mejram.sln
before_build:
  - psql -c "CREATE DATABASE sakila;" -U postgres
  - psql -c "CREATE USER test WITH PASSWORD 'test';" -U postgres
build:
  project: ./csharp/Mejram.sln
  verbosity: minimal
services:
  - postgresql
