services:
  pg:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      #POSTGRES_DB: pakila
    #volumes: 
    #  - ./sakila/postgres-sakila-db:/db-import
    #  - ./pg:/docker-entrypoint-initdb.d # https://stackoverflow.com/questions/74705161/scripts-in-the-docker-entrypoint-initdb-d-folder-are-ignored ?
    ports:
      - "5434:5432"

  mssql:
    image: mcr.microsoft.com/mssql/server
    restart: always
    environment:
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      ACCEPT_EULA: Y
      MSSQL_PID: Developer
    ports:
      - "5433:1433"
