services:
  pg:
    # ConnectionString=
    #   Host=pg;
    #   Database=pakila;
    #   Username=postgres;
    #   Password=${POSTGRES_PASSWORD};
    #   Port=5432;
    image: postgres
    #restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: pakila
    volumes: 
      - ./jOOQ/jOOQ-examples/Sakila/postgres-sakila-db:/db-import
      - ./pg:/docker-entrypoint-initdb.d # https://stackoverflow.com/questions/74705161/scripts-in-the-docker-entrypoint-initdb-d-folder-are-ignored ?
    ports:
      - "5434:5432"

  mssql:
    # ConnectionString=
    #   Server=mssql;
    #   Database=sakila;
    #   User Id=sa;
    #   Password=${MSSQL_SA_PASSWORD}
    image: mcr.microsoft.com/mssql/server

    environment:
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      ACCEPT_EULA: Y
      MSSQL_PID: Developer
    ports:
      - "5433:1433"
